"use client";

import { useState } from "react";
import { Copy, Download, Container, Settings, Zap, ShieldCheck, Activity, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import { ToolLayout } from "@/components/ToolLayout";

const DockerfileGenerator = () => {
  const [baseImage, setBaseImage] = useState("node:18-alpine");
  const [workDir, setWorkDir] = useState("/app");
  const [copyFiles, setCopyFiles] = useState("package*.json ./");
  const [runCommands, setRunCommands] = useState("npm install");
  const [exposePort, setExposePort] = useState("3000");
  const [startCommand, setStartCommand] = useState("npm start");
  const [addHealthcheck, setAddHealthcheck] = useState(false);
  const [addMultiStage, setAddMultiStage] = useState(false);
  const [dockerfile, setDockerfile] = useState("");
  const { toast } = useToast();

  const generateDockerfile = () => {
    let content = `### GENERATED BY UTIL.DEV ###\n\n`;

    if (addMultiStage) {
      content += `# Build Stage\n`;
      content += `FROM ${baseImage} AS builder\n`;
      content += `WORKDIR ${workDir}\n\n`;
      content += `COPY ${copyFiles}\n`;
      content += `RUN ${runCommands}\n\n`;
      content += `# Production Stage\n`;
      content += `FROM ${baseImage} AS production\n`;
      content += `WORKDIR ${workDir}\n\n`;
      content += `COPY --from=builder ${workDir} .\n\n`;
    } else {
      content += `FROM ${baseImage}\n\n`;
      content += `# Set working directory\n`;
      content += `WORKDIR ${workDir}\n\n`;
      content += `# Copy dependency files\n`;
      content += `COPY ${copyFiles}\n\n`;
      content += `# Install dependencies\n`;
      content += `RUN ${runCommands}\n\n`;
      content += `# Copy source code\n`;
      content += `COPY . .\n\n`;
    }

    if (exposePort) {
      content += `# Expose application port\n`;
      content += `EXPOSE ${exposePort}\n\n`;
    }

    if (addHealthcheck) {
      content += `# Healthcheck configuration\n`;
      content += `HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\\n`;
      content += `  CMD curl -f http://localhost:${exposePort}/health || exit 1\n\n`;
    }

    content += `# Execution command\n`;
    const parts = startCommand.split(' ');
    content += `CMD ["${parts[0]}", ${parts.slice(1).map(p => `"${p}"`).join(', ')}]`;

    setDockerfile(content);
    toast({ title: "Generated!", description: "Dockerfile is ready to use" });
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(dockerfile);
    toast({ title: "Copied!", description: "Dockerfile copied to clipboard" });
  };

  const downloadDockerfile = () => {
    const blob = new Blob([dockerfile], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Dockerfile';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <ToolLayout
      title="Dockerfile Architect"
      description="Quickly generate production-ready Docker configurations for any runtime"
      category="DevOps & Deploy"
      icon={Container}
    >
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Config */}
        <Card className="lg:col-span-1 bg-card border-border card-glow">
          <CardHeader>
            <CardTitle className="font-mono text-sm flex items-center gap-2">
              <Settings className="w-4 h-4 text-primary" />
              Build Parameters
            </CardTitle>
            <CardDescription className="text-xs">Define your image layers</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Base Runtime</label>
              <Select value={baseImage} onValueChange={setBaseImage}>
                <SelectTrigger className="bg-muted/20 border-border font-mono text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="font-mono text-xs">
                  <SelectItem value="node:18-alpine">Node.js 18 (Alpine)</SelectItem>
                  <SelectItem value="node:20-slim">Node.js 20 (Slim)</SelectItem>
                  <SelectItem value="python:3.11-slim">Python 3.11 (Slim)</SelectItem>
                  <SelectItem value="golang:1.21-alpine">Go 1.21 (Alpine)</SelectItem>
                  <SelectItem value="rust:1.75-slim">Rust 1.75 (Slim)</SelectItem>
                  <SelectItem value="nginx:stable-alpine">Nginx Stable</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Work Directory</label>
              <Input
                value={workDir}
                onChange={(e) => setWorkDir(e.target.value)}
                className="font-mono text-xs bg-muted/20 border-border"
              />
            </div>

            <div className="space-y-4 pt-2">
              <div className="flex items-center justify-between p-3 border border-border rounded-xl bg-muted/10">
                <div className="space-y-0.5">
                  <label htmlFor="multistage" className="text-xs font-bold text-foreground cursor-pointer">Multi-stage Build</label>
                  <p className="text-[10px] text-muted-foreground">Optimize image size</p>
                </div>
                <Checkbox
                  id="multistage"
                  checked={addMultiStage}
                  onCheckedChange={(checked) => setAddMultiStage(checked === true)}
                  className="border-primary data-[state=checked]:bg-primary"
                />
              </div>

              <div className="flex items-center justify-between p-3 border border-border rounded-xl bg-muted/10">
                <div className="space-y-0.5">
                  <label htmlFor="healthcheck" className="text-xs font-bold text-foreground cursor-pointer">Add Healthcheck</label>
                  <p className="text-[10px] text-muted-foreground">Automatic recovery status</p>
                </div>
                <Checkbox
                  id="healthcheck"
                  checked={addHealthcheck}
                  onCheckedChange={(checked) => setAddHealthcheck(checked === true)}
                  className="border-primary data-[state=checked]:bg-primary"
                />
              </div>
            </div>

            <Button onClick={generateDockerfile} className="w-full h-11 font-mono bg-primary hover:bg-primary/90 mt-4 shadow-lg shadow-primary/10">
              <Zap className="w-4 h-4 mr-2" />
              Generate Architect
            </Button>
          </CardContent>
        </Card>

        {/* Right Column: Code Output */}
        <Card className="lg:col-span-2 bg-card border-border card-glow flex flex-col">
          <CardHeader className="pb-3 border-b border-border bg-muted/20">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="font-mono text-sm flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-primary" />
                  Generated Layer Config
                </CardTitle>
                <CardDescription className="text-xs font-mono">/Dockerfile</CardDescription>
              </div>
              <div className="flex gap-2">
                <Button size="icon" variant="ghost" className="h-8 w-8 text-muted-foreground hover:text-primary" onClick={copyToClipboard} disabled={!dockerfile}>
                  <Copy className="w-4 h-4" />
                </Button>
                <Button size="icon" variant="ghost" className="h-8 w-8 text-muted-foreground hover:text-primary" onClick={downloadDockerfile} disabled={!dockerfile}>
                  <Download className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent className="flex-1 p-0">
            <Textarea
              value={dockerfile}
              readOnly
              className="min-h-[500px] h-full border-0 rounded-none font-mono text-xs bg-muted/5 p-6 leading-relaxed resize-none focus-visible:ring-0"
              placeholder="# Your configuration will appear here..."
            />
          </CardContent>
          {dockerfile && (
            <div className="p-4 border-t border-border bg-card flex justify-end gap-3">
              <Button variant="outline" size="sm" onClick={copyToClipboard} className="font-mono text-xs">
                <Copy className="w-3.5 h-3.5 mr-2" />
                Copy to Clipboard
              </Button>
              <Button size="sm" onClick={downloadDockerfile} className="font-mono text-xs">
                <Download className="w-3.5 h-3.5 mr-2" />
                Download File
              </Button>
            </div>
          )}
        </Card>

        {/* Advanced Config Banner */}
        <Card className="lg:col-span-3 bg-muted/30 border-border">
          <CardContent className="p-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-2">
                  <Activity className="w-3 h-3 text-primary" />
                  Network Entry
                </label>
                <Input
                  placeholder="Port (e.g. 3000)"
                  value={exposePort}
                  onChange={(e) => setExposePort(e.target.value)}
                  className="font-mono text-xs bg-card border-border"
                />
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-2">
                  <Container className="w-3 h-3 text-primary" />
                  Source Mapping
                </label>
                <Input
                  placeholder="COPY command"
                  value={copyFiles}
                  onChange={(e) => setCopyFiles(e.target.value)}
                  className="font-mono text-xs bg-card border-border"
                />
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-2">
                  <Zap className="w-3 h-3 text-primary" />
                  EntryPoint Execution
                </label>
                <Input
                  placeholder="Start script"
                  value={startCommand}
                  onChange={(e) => setStartCommand(e.target.value)}
                  className="font-mono text-xs bg-card border-border"
                />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Pro Tip Card */}
        <Card className="lg:col-span-3 bg-primary/5 border-primary/20">
          <CardContent className="p-6 flex gap-4 items-start">
            <Info className="w-6 h-6 text-primary shrink-0" />
            <div className="space-y-1">
              <h4 className="font-bold font-mono text-xs uppercase tracking-widest">Best Practice Tip</h4>
              <p className="text-[11px] font-mono text-muted-foreground leading-relaxed">
                Always use <span className="text-primary">-alpine</span> or <span className="text-primary">-slim</span> variants for base images to minimize your container's attack surface and deployment time. Multi-stage builds are highly recommended for compiled languages or frontend frameworks to keep the runtime image lean.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </ToolLayout>
  );
};

export default DockerfileGenerator;
