"use client";

import { useState } from "react";
import { Search, Copy, Download, Plus, FileCode, Check, Trash2, Info, Terminal, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import { ToolLayout } from "@/components/ToolLayout";

const GitignoreGenerator = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);
  const [customRules, setCustomRules] = useState("");
  const [generatedGitignore, setGeneratedGitignore] = useState("");
  const { toast } = useToast();

  const templates = [
    { name: "Node.js", content: "node_modules/\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n.npm\n.yarn-integrity\n.env\n.env.*" },
    { name: "Next.js", content: ".next/\nout/\nbuild/\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local" },
    { name: "React", content: "build/\ndist/\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local" },
    { name: "Python", content: "__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nbuild/\ndist/\n*.egg-info/\n.venv/" },
    { name: "Java", content: "*.class\n*.log\ntarget/\n.idea/\n.project\n.settings/" },
    { name: "Go", content: "*.exe\n*.exe~\n*.dll\n*.so\n*.dylib\nvendor/" },
    { name: "Rust", content: "target/\n**/*.rs.bk\nCargo.lock" },
    { name: "Android", content: "*.apk\nbin/\ngen/\nout/\n.gradle/\nbuild/" },
    { name: "Unity", content: "[Ll]ibrary/\n[Tt]emp/\n[Oo]bj/\n[Bb]uild/\n[Ll]ogs/" },
    { name: "Laravel", content: "/vendor/\nnode_modules/\n.env\n*.key" }
  ];

  const filteredTemplates = templates.filter(template =>
    template.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const toggleTemplate = (templateName: string) => {
    setSelectedTemplates(prev =>
      prev.includes(templateName)
        ? prev.filter(name => name !== templateName)
        : [...prev, templateName]
    );
  };

  const generateGitignore = () => {
    let content = "### Generated by Util.dev ###\n\n";

    selectedTemplates.forEach(templateName => {
      const template = templates.find(t => t.name === templateName);
      if (template) {
        content += `# [Template: ${template.name}]\n${template.content}\n\n`;
      }
    });

    if (customRules.trim()) {
      content += "# [Custom Rules]\n" + customRules.trim() + "\n";
    }

    if (selectedTemplates.length === 0 && !customRules.trim()) {
      toast({ title: "Empty Selection", description: "Select templates or add custom rules", variant: "destructive" });
      return;
    }

    setGeneratedGitignore(content);
    toast({ title: "Generated", description: "Security profile merged successfully" });
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedGitignore);
    toast({ title: "Copied!", description: "Gitignore content copied to clipboard" });
  };

  const downloadGitignore = () => {
    const blob = new Blob([generatedGitignore], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.gitignore';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <ToolLayout
      title="Gitignore Weaver"
      description="Professional-grade .gitignore generation using industry standard templates"
      category="Developer Tools"
      icon={FileCode}
    >
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Template Selector */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="bg-card border-border card-glow h-full flex flex-col">
            <CardHeader className="pb-3">
              <CardTitle className="font-mono text-sm flex items-center gap-2">
                <Terminal className="w-4 h-4 text-primary" />
                Template Registry
              </CardTitle>
            </CardHeader>
            <CardContent className="flex-1 space-y-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-3.5 h-3.5" />
                <Input
                  placeholder="Filter stacks..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-9 font-mono text-xs bg-muted/10 border-border h-9"
                />
              </div>

              <div className="space-y-1 overflow-y-auto max-h-[400px] pr-2 custom-scrollbar">
                {filteredTemplates.map((template) => (
                  <div
                    key={template.name}
                    onClick={() => toggleTemplate(template.name)}
                    className={`flex items-center justify-between p-3 rounded-xl border transition-all cursor-pointer group ${selectedTemplates.includes(template.name)
                        ? 'border-primary/50 bg-primary/5 text-primary'
                        : 'border-border bg-muted/5 text-muted-foreground hover:border-primary/30'
                      }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className={`w-5 h-5 rounded flex items-center justify-center border transition-colors ${selectedTemplates.includes(template.name) ? 'bg-primary border-primary text-white' : 'border-border group-hover:border-primary/30'
                        }`}>
                        {selectedTemplates.includes(template.name) && <Check className="w-3 h-3" />}
                      </div>
                      <span className="text-xs font-mono font-bold uppercase tracking-wider">{template.name}</span>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
            <div className="p-4 border-t border-border bg-muted/5">
              <Button onClick={generateGitignore} className="w-full h-10 font-mono bg-primary hover:bg-primary/90 text-xs">
                <Plus className="w-3.5 h-3.5 mr-2" />
                Compile .gitignore
              </Button>
            </div>
          </Card>
        </div>

        {/* Center: Custom & Output */}
        <div className="lg:col-span-2 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="bg-card border-border card-glow">
              <CardHeader className="pb-3 border-b border-border bg-muted/10">
                <CardTitle className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Custom Logic</CardTitle>
              </CardHeader>
              <CardContent className="pt-4">
                <Textarea
                  placeholder="# manual rules&#10;*.log&#10;/build"
                  value={customRules}
                  onChange={(e) => setCustomRules(e.target.value)}
                  className="min-h-[150px] font-mono text-xs bg-transparent border-0 focus-visible:ring-0 resize-none p-0"
                />
              </CardContent>
            </Card>

            <Card className="bg-primary/5 border-primary/20">
              <CardHeader className="pb-3 border-b border-primary/10">
                <CardTitle className="font-mono text-[10px] uppercase tracking-widest text-primary">Active Stacks</CardTitle>
              </CardHeader>
              <CardContent className="pt-4">
                <div className="flex flex-wrap gap-2">
                  {selectedTemplates.length > 0 ? selectedTemplates.map(t => (
                    <Badge key={t} variant="outline" className="bg-primary/10 border-primary/30 text-primary font-mono text-[9px] h-6">
                      {t}
                    </Badge>
                  )) : (
                    <span className="text-[10px] italic text-muted-foreground font-mono">No templates active</span>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="bg-card border-border card-glow flex flex-col h-full">
            <CardHeader className="pb-3 border-b border-border bg-muted/20">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="font-mono text-sm flex items-center gap-2">
                    <Zap className="w-4 h-4 text-amber-500" />
                    Generated Manifest
                  </CardTitle>
                  <CardDescription className="text-xs font-mono">.gitignore</CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button size="icon" variant="ghost" className="h-8 w-8 text-muted-foreground hover:text-primary" onClick={copyToClipboard} disabled={!generatedGitignore}>
                    <Copy className="w-4 h-4" />
                  </Button>
                  <Button size="icon" variant="ghost" className="h-8 w-8 text-muted-foreground hover:text-primary" onClick={downloadGitignore} disabled={!generatedGitignore}>
                    <Download className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex-1 p-0">
              <Textarea
                value={generatedGitignore}
                readOnly
                className="min-h-[400px] h-full border-0 rounded-none font-mono text-[11px] bg-muted/5 p-6 leading-relaxed resize-none focus-visible:ring-0"
                placeholder="# The manifest will be compiled here..."
              />
            </CardContent>
            {generatedGitignore && (
              <div className="p-4 border-t border-border bg-card flex justify-end gap-3">
                <Button variant="ghost" size="sm" onClick={() => setGeneratedGitignore("")} className="font-mono text-[10px] text-muted-foreground hover:text-destructive">
                  <Trash2 className="w-3.5 h-3.5 mr-2" />
                  Clear
                </Button>
                <Button size="sm" onClick={downloadGitignore} className="font-mono text-xs">
                  <Download className="w-3.5 h-3.5 mr-2" />
                  Save Manifest
                </Button>
              </div>
            )}
          </Card>
        </div>

        <Card className="lg:col-span-3 bg-muted/20 border-border">
          <CardContent className="p-6 flex gap-6 items-center">
            <Info className="w-8 h-8 text-primary opacity-50 shrink-0" />
            <p className="text-[11px] font-mono text-muted-foreground leading-relaxed">
              <strong>Gitignore Weaver</strong> aggregates industry-standard ignore patterns from the official Git community repositories.
              Selecting multiple templates will merge them into a single, cohesive manifest.
              Always verify the rules before committing to your repository.
            </p>
          </CardContent>
        </Card>
      </div>
    </ToolLayout>
  );
};

export default GitignoreGenerator;
