"use client";


import { useState } from "react";
import { Search, Copy, Download, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";

const GitignoreGenerator = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);
  const [customRules, setCustomRules] = useState("");
  const [generatedGitignore, setGeneratedGitignore] = useState("");
  const { toast } = useToast();

  const templates = [
    { name: "Node.js", content: "node_modules/\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n.npm\n.yarn-integrity\n.env\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local" },
    { name: "React", content: "build/\ndist/\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*" },
    { name: "Python", content: "__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nbuild/\ndevelop-eggs/\ndist/\ndownloads/\neggs/\n.eggs/\nlib/\nlib64/\nparts/\nsdist/\nvar/\nwheels/\n*.egg-info/\n.installed.cfg\n*.egg\nPIPFILE.lock" },
    { name: "Java", content: "*.class\n*.log\n*.ctxt\n.mtj.tmp/\n*.jar\n*.war\n*.nar\n*.ear\n*.zip\n*.tar.gz\n*.rar\nhs_err_pid*\ntarget/\npom.xml.tag\npom.xml.releaseBackup\npom.xml.versionsBackup\npom.xml.next\nrelease.properties\ndependency-reduced-pom.xml\nbuildNumber.properties\n.mvn/timing.properties\n.mvn/wrapper/maven-wrapper.jar" },
    { name: "C++", content: "*.o\n*.obj\n*.exe\n*.out\n*.app\n*.i*86\n*.x86_64\n*.hex\n*.dSYM/\n*.su\n*.idb\n*.pdb" },
    { name: "Go", content: "*.exe\n*.exe~\n*.dll\n*.so\n*.dylib\n*.test\n*.out\ngo.work\nvendor/" },
    { name: "Rust", content: "target/\n**/*.rs.bk\n*.pdb\nCargo.lock" },
    { name: "Android", content: "*.apk\n*.ap_\n*.aab\n*.dex\n*.class\nbin/\ngen/\nout/\n.gradle/\nbuild/\nlocal.properties\nproguard/\n*.log\n*.keystore\n!debug.keystore" },
    { name: "iOS", content: "*.xcodeproj/*\n!*.xcodeproj/project.pbxproj\n!*.xcworkspace/contents.xcworkspacedata\n/*.gcno\n**/xcuserdata/\n*.moved-aside\nDerivedData\n*.hmap\n*.ipa\n*.xcuserstate\nproject.xcworkspace\nxcuserdata/" },
    { name: "Unity", content: "[Ll]ibrary/\n[Tt]emp/\n[Oo]bj/\n[Bb]uild/\n[Bb]uilds/\n[Ll]ogs/\n[Mm]emoryCaptures/\n/[Aa]ssets/AssetStoreTools*\n/[Aa]ssets/Plugins/Editor/JetBrains*\n[Aa]ssets/StreamingAssets/aa.meta\n[Aa]ssets/StreamingAssets/aa/*" },
    { name: "WordPress", content: "*.log\nwp-config.php\nwp-content/advanced-cache.php\nwp-content/backup-db/\nwp-content/backups/\nwp-content/blogs.dir/\nwp-content/cache/\nwp-content/upgrade/\nwp-content/uploads/\nwp-content/mu-plugins/\nwp-content/wp-cache-config.php\nwp-content/plugins/hello.php\n/.htaccess\n/license.txt\n/readme.html\n/sitemap.xml\n/sitemap.xml.gz" },
    { name: "Laravel", content: "/vendor/\nnode_modules/\nnpm-debug.log\nyarn-error.log\n.env\n.env.backup\n.phpunit.result.cache\nHomestead.json\nHomestead.yaml\nauth.json\n*.key\n.phpstorm.meta.php\n/_ide_helper.php\n.phpstorm.meta.php\n/_ide_helper_models.php\n/.vscode" }
  ];

  const filteredTemplates = templates.filter(template =>
    template.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const toggleTemplate = (templateName: string) => {
    setSelectedTemplates(prev =>
      prev.includes(templateName)
        ? prev.filter(name => name !== templateName)
        : [...prev, templateName]
    );
  };

  const generateGitignore = () => {
    let content = "# Generated by DevKit Hub\n\n";
    
    selectedTemplates.forEach(templateName => {
      const template = templates.find(t => t.name === templateName);
      if (template) {
        content += `# ${template.name}\n${template.content}\n\n`;
      }
    });
    
    if (customRules.trim()) {
      content += "# Custom Rules\n" + customRules.trim() + "\n";
    }
    
    if (selectedTemplates.length === 0 && !customRules.trim()) {
      toast({
        title: "Nothing to generate",
        description: "Please select templates or add custom rules",
        variant: "destructive"
      });
      return;
    }
    
    setGeneratedGitignore(content);
    toast({
      title: "Generated!",
      description: "Gitignore file has been generated"
    });
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedGitignore);
    toast({ title: "Copied!", description: "Gitignore content copied to clipboard" });
  };

  const downloadGitignore = () => {
    const blob = new Blob([generatedGitignore], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.gitignore';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-foreground">Gitignore Generator</h1>
          <p className="text-muted-foreground">Generate .gitignore files for your projects</p>
          <Badge className="bg-purple-100 text-purple-700 border-purple-200 mt-2">Developer Tools</Badge>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Select Templates</CardTitle>
                <CardDescription>Choose templates for your project type</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 w-4 h-4" />
                    <Input
                      placeholder="Search templates..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="pl-10"
                    />
                  </div>
                  
                  <div className="space-y-2 max-h-64 overflow-y-auto">
                    {filteredTemplates.map((template) => (
                      <div key={template.name} className="flex items-center space-x-2">
                        <Checkbox
                          id={template.name}
                          checked={selectedTemplates.includes(template.name)}
                          onCheckedChange={() => toggleTemplate(template.name)}
                        />
                        <label
                          htmlFor={template.name}
                          className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
                        >
                          {template.name}
                        </label>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Custom Rules</CardTitle>
                <CardDescription>Add your own gitignore patterns</CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  placeholder="# Custom gitignore rules&#10;*.tmp&#10;secrets.json&#10;/build&#10;!important.txt"
                  value={customRules}
                  onChange={(e) => setCustomRules(e.target.value)}
                  className="min-h-[200px] font-mono text-sm"
                />
              </CardContent>
            </Card>

            <Button onClick={generateGitignore} className="w-full bg-blue-600 hover:bg-blue-700">
              <Plus className="w-4 h-4 mr-2" />
              Generate .gitignore
            </Button>
          </div>

          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Generated .gitignore</CardTitle>
                  <CardDescription>Your custom gitignore file</CardDescription>
                </div>
                {generatedGitignore && (
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={copyToClipboard}>
                      <Copy className="w-4 h-4" />
                    </Button>
                    <Button size="sm" onClick={downloadGitignore}>
                      <Download className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                  </div>
                )}
              </div>
            </CardHeader>
            <CardContent>
              <Textarea
                value={generatedGitignore}
                readOnly
                className="min-h-[500px] font-mono text-sm bg-muted"
                placeholder="Generated .gitignore will appear here..."
              />
            </CardContent>
          </Card>
        </div>

        {selectedTemplates.length > 0 && (
          <Card className="mt-6">
            <CardHeader>
              <CardTitle>Selected Templates</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {selectedTemplates.map((template) => (
                  <Badge key={template} variant="outline" className="px-3 py-1">
                    {template}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default GitignoreGenerator;
